# -*- coding: utf-8 -*-
"""Task6_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6XBActqkMge-PZuKCzUEJrMJM_Xdecp
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("retail.csv")
df.head()

df.info()

promo_footfall = df.groupby("promotion_intensity")["footfall"].mean()

plt.figure(figsize=(10,5))
plt.bar(promo_footfall.index, promo_footfall.values)
plt.xlabel("Promotion Intensity")
plt.ylabel("Average Footfall")
plt.title("Promotion Intensity vs Average Footfall")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(10,5))
plt.plot(df.index, df["footfall"])
plt.xlabel("Record Index")
plt.ylabel("Footfall")
plt.title("Footfall Trend")
plt.grid()
plt.show()

plt.figure(figsize=(8,5))
plt.hist(df["return_rate"], bins=25)
plt.xlabel("Return Rate")
plt.ylabel("Frequency")
plt.title("Return Rate Distribution")
plt.grid()
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(df["ad_spend"], df["footfall"])
plt.xlabel("Ad Spend")
plt.ylabel("Footfall")
plt.title("Ad Spend vs Footfall")
plt.grid()
plt.show()

max_footfall = df.loc[df["footfall"].idxmax()]

plt.figure(figsize=(8,5))
plt.scatter(df["ad_spend"], df["footfall"])
plt.scatter(max_footfall["ad_spend"], max_footfall["footfall"])
plt.text(max_footfall["ad_spend"], max_footfall["footfall"], "Highest Footfall")
plt.xlabel("Ad Spend")
plt.ylabel("Footfall")
plt.title("Ad Spend vs Footfall (Highest Highlighted)")
plt.grid()
plt.show()